//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_QLDoDienTu_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiaChi
    {
        public int MaDiaChi { get; set; }
        public string TenDN { get; set; }
        public string DiaChi1 { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
