//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_QLDoDienTu_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioHang
    {
        public string TenDN { get; set; }
        public int MaCTSanPham { get; set; }
        public string TenSanPham { get; set; }
        public string Anh { get; set; }
        public Nullable<double> Gia { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string KichThuoc { get; set; }
        public Nullable<double> ThanhTien { get; set; }
        public Nullable<int> TrangThaiGH { get; set; }
    
        public virtual ChiTietSanPham ChiTietSanPham { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
